// <auto-generated />
using System;
using CodeEditor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeEditor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250427230547_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("CodeEditor.Core.Entities.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("CodeEditor.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentationUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExecutable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RunCommand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentationUrl = "https://docs.python.org/3/",
                            Extensions = ".py",
                            IsExecutable = true,
                            Name = "Python",
                            RunCommand = "python \"{0}\""
                        },
                        new
                        {
                            Id = 2,
                            DocumentationUrl = "https://perldoc.perl.org/",
                            Extensions = ".pl",
                            IsExecutable = true,
                            Name = "Perl",
                            RunCommand = "perl \"{0}\""
                        },
                        new
                        {
                            Id = 3,
                            DocumentationUrl = "https://learn.microsoft.com/en-us/dotnet/csharp/",
                            Extensions = ".cs,.csproj",
                            IsExecutable = true,
                            Name = "C#",
                            RunCommand = "dotnet run --project \"{0}\""
                        },
                        new
                        {
                            Id = 4,
                            DocumentationUrl = "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
                            Extensions = ".js",
                            IsExecutable = true,
                            Name = "JavaScript",
                            RunCommand = "node \"{0}\""
                        },
                        new
                        {
                            Id = 5,
                            DocumentationUrl = "https://developer.mozilla.org/en-US/docs/Web/HTML",
                            Extensions = ".html,.htm",
                            IsExecutable = false,
                            Name = "HTML",
                            RunCommand = ""
                        },
                        new
                        {
                            Id = 6,
                            DocumentationUrl = "https://developer.mozilla.org/en-US/docs/Web/CSS",
                            Extensions = ".css",
                            IsExecutable = false,
                            Name = "CSS",
                            RunCommand = ""
                        },
                        new
                        {
                            Id = 7,
                            DocumentationUrl = "https://www.w3schools.com/sql/",
                            Extensions = ".sql",
                            IsExecutable = false,
                            Name = "SQL",
                            RunCommand = ""
                        },
                        new
                        {
                            Id = 8,
                            DocumentationUrl = "https://www.json.org/json-en.html",
                            Extensions = ".json",
                            IsExecutable = false,
                            Name = "JSON",
                            RunCommand = ""
                        },
                        new
                        {
                            Id = 9,
                            DocumentationUrl = "https://yaml.org/",
                            Extensions = ".yml,.yaml",
                            IsExecutable = false,
                            Name = "YAML",
                            RunCommand = ""
                        },
                        new
                        {
                            Id = 10,
                            DocumentationUrl = "https://www.markdownguide.org/",
                            Extensions = ".md,.markdown",
                            IsExecutable = false,
                            Name = "Markdown",
                            RunCommand = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
